<template>
  <div id="app">
    <h1>Viinit</h1>
    <wine-form @add:wine="addWine"/>
    <wine-table
      :dataLoaded="dataLoaded" :wines="wines"
      @delete:wine="deleteWine" @edit:wine="editWine"/>
  </div>
</template>

<script>
  import WineForm from "@/components/WineForm.vue"
  import WineTable from "@/components/WineTable.vue"
  import { WineService } from "@/services/WineService.js";
  import { wineStore } from "@/stores/wineStore.js";

  const wineService = new WineService(wineStore);

  export default {
    name: "app",
    components: {
      WineForm,
      WineTable
    },

    data() {
      return {
        dataLoaded: false,
        wines: wineStore.state.wines
      }
    },

    mounted() {
      this.getWines();
    },

    methods: {
      async getWines() { wineService.getWines() },
      async getWine(id) { wineService.getWine(id) },
      async addWine(wine) {
        // TODO: remove ID generation. IDs are generated by the database.
        const lastId = this.wines.length > 0 ? this.wines[this.wines.length - 1].id : 0;
        const id = lastId + 1;
        const newWine = {...wine, id};
        this.wines = [...this.wines, newWine];

        wineService.addWine(wine);
      },
      async editWine(id, editedWine) { wineService.edit(id, editedWine) },
      async deleteWine(id) { wineService.deleteWine(id) }
    },
  }
    
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
