<template>
  <div id="app">
    <h1>Viinit</h1>
    <wine-form @add:wine="addWine"/>
    <wine-table :wines="wines" @delete:wine="deleteWine" @edit:wine="editWine"/>
  </div>
</template>

<script>
import axios from "axios"
import WineForm from "@/components/WineForm.vue"
import WineTable from "@/components/WineTable.vue"

export default {
  name: "app",
  components: {
    WineForm,
    WineTable
  },
  data() {
    return {
      wines: []
    }
  },
  mounted() {
    this.getWines();
  },
  // TODO: Move CRUD methods to service component.
  methods: {
    async getWines() {
      axios.get("http://localhost:8080/api/wines")
        .then((response) => this.wines = response.data)
        .catch((error) => console.log(error));
    },
    addWine(wine) {
      // TODO: remove ID generation. IDs are generated by the database.
      const lastId = this.wines.length > 0 ? this.wines[this.wines.length - 1].id : 0;
      const id = lastId + 1;
      const newWine = {...wine, id};
      this.wines = [...this.wines, newWine];
    },
    deleteWine(id) {
      this.wines = this.wines.filter(wine => wine.id !== id);
    },
    editWine(id, editedWine) {
      this.wines = this.wines.map(wine => wine.id === id ? editedWine : wine);
    }
  }
}
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
