# Workflow for development branches.
# Runs linter and tests on push.

name: Development branch, Node.js

on:
  push:
    branches-ignore:
     - master
     - release*

jobs:
  test:
    name: Run linter and tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run lint
    - run: npm test
      env:
        CI: true
