# Workflow for development branches.
# Runs linter and tests on push.

name: Development branch, Node.js

on:
  push:
    branches-ignore:
     - master
     - release*

jobs:
  test:
    name: Run linter and tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint
    - run: npm test
      env:
        CI: true
